### ISSUE TITLE
9.1.2 Broken?

### ISSUE THREAD

**Issue by DandyDeveloper** [siemens/sentry-auth-oidc#17]
Looks like the plugin is either broken, or I've misconfigured it on 9.1.2. 

I've installed it, but it's breaking the auth-providers page because it's returning a null name in the response:

``` json
[{"requiredFeature": "organizations:sso-basic", "name": "Google", "key": "google"}, {"requiredFeature": "organizations:sso-basic", "name": null, "key": "oidc"}]
```

Any ideas on the best way to fix this?

**Comment by DandyDeveloper** [comment]
Looks like it's actually a case of the docker image not using the sentry config properly, or the `OIDC_ISSUER` being mandatory. 

Follow up issue. When authenticating, auth helper to add a user is failing:

``` python
xxxx  - - [15/Nov/2019:05:31:36 +0000] "GET /auth/sso/?code=vyfldkmbvru2cvt7ggdctg4ru&state=ce0cb854fbc346cb8ea4aa8313230c78 HTTP/1.1" 200 5840 "https://sso.url/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36"
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 225, in dispatch
    return self.handle(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/auth_provider_login.py", line 19, in handle
    return helper.current_step()
  File "/usr/local/lib/python2.7/site-packages/sentry/auth/helper.py", line 626, in current_step
    return self.finish_pipeline()
  File "/usr/local/lib/python2.7/site-packages/sentry/auth/helper.py", line 655, in finish_pipeline
    response = self._finish_login_pipeline(identity)
  File "/usr/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/auth/helper.py", line 713, in _finish_login_pipeline
    identity,
  File "/usr/local/lib/python2.7/site-packages/sentry/auth/helper.py", line 412, in handle_unknown_identity
    auth_identity = handle_new_user(auth_provider, organization, request, identity)
  File "/usr/local/lib/python2.7/site-packages/sentry/auth/helper.py", line 484, in handle_new_user
    name=identity.get('name', '')[:200],
TypeError: 'NoneType' object has no attribute '__getitem__'
05:31:40 [ERROR] django.request: Internal Server Error: /auth/sso/ (request_id=u'aa3ccc16bf13df1b53f50ab655405d52' status_code=500 request=<WSGIRequest: POST u'/auth/sso/?code=vyfldkmbvru2cvt7ggdctg4ru&state=ce0cb854fbc346cb8ea4aa8313230c78'>)
xxxx - - [15/Nov/2019:05:31:39 +0000] "POST /auth/sso/?code=vyfldkmbvru2cvt7ggdctg4ru&state=ce0cb854fbc346cb8ea4aa8313230c78 HTTP/1.1" 500 6031 "https://sso.url/auth/sso/?code=vyfldkmbvru2cvt7ggdctg4ru&state=ce0cb85
```

**Comment by DandyDeveloper** [comment]
Closing as it just seems to be more Sentry backend expecting certain values, adding sufficient OIDC parameters fixed this.
